# This file stores the secure values for the app
# Includes things like private usernames, and passwords
default:
  private_key: "~/private_key.pem"
  sqlite_username : "keys/sqlite_username.pem"
  sqlite_password: "keys/sqlite_password.pem"
  public_key: "keys/public_key.pem"
  